### ISSUE TITLE
Preferred `scan.execute` behaviour (API)

### ISSUE THREAD

**Issue by JCZuurmond** [sodadata/soda-spark#23]
**What is the preferred behavior for the `scan.execute` from a user perspective?**

At this moment the [`execute`](https://github.com/sodadata/soda-spark/blob/8f2d90ca1b3ce5a05e8694dd9e4ce1ebc1bbad8b/src/sodaspark/scan.py#L194) returns a Spark data frame. The data frame contains the measurements of the`scan_results`. 

Maybe it does not make sense to returns this a Spark data frame: 
- we are doing an extra python -> spark conversion. 
- if changes are made to the scan results, then we need to update the logic here too. 

We could return the scan result object. However, that is maybe not an object the user expects, as it is Soda internal.

**Comment by fakirAyoub** [comment]
Hey @JCZuurmond 

Following up on our discussion in Soda's Community Slack, since spark-sql is going to be used with developers as main users, it would be best to be able to run scan functions separately, rather than running an execute which only some of the results might help the data engineer using the tool.

IMHO, this part of `soda-spark` needs to be designed as a library, rather than a config driven tool.

Happy to chat/help!

**Comment by JCZuurmond** [comment]
The discussion about data frames is held at #95. I am closing this issue since it it too broad.
